# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
#name: Brett Harris
name: Daniel Gleason
#title: This is a test title
title: Master's Student, York University
email: daniel.gleason@outlook.com
#website: https://dgleaso.github.io/

# Social links
#twitter_username: facespics
github_username:  dgleaso
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: daniel-gleason-069a1aa4
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
        My name is Daniel and I'm a Master's Student at York University.  I am working towards a Master of Science in Computer Science with a Specialization in Artificial Intelligence, a program officially recognized by the [Vector Institute](https://vectorinstitute.ai/).


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
