# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
#name: Brett Harris
name: Daniel Gleason
#title: This is a test title
#title: Master's Student, Specialization in Artificial Intelligence > York University
#title: > 
#Master's Student, Specialization in Artificial Intelligence 
#        York University
title: Master's Student, Specialization in Artificial Intelligence, York University
email: daniel.gleason@outlook.com
#website: https://dgleaso.github.io/

# Social links
#twitter_username: facespics
github_username:  dgleaso
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: daniel-gleason-069a1aa4
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
        My name is Daniel and I'm a Master's Student at York University.  I am working towards a Master of Science in Computer Science with a Specialization in Artificial Intelligence,
        a program officially recognized by the [Vector Institute](https://vectorinstitute.ai/).

        I am excited to be working in the field of Machine Learning. I am particularly interesting in Deep Reinforcement Learning, which I am exploring in my Master's industry project. 
        I have experience working with <mark>PyTorch</mark> and <mark>TensorFlow</mark>.
        
        Once I complete my Master's degree, I hope to apply my knowledge of Machine Learning to interesting and challenging problems in industry.

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
        I also competed in Varsity pole vaulting.  Talk more here, maybe put video as well.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
